[package]
name = "alkanes-web-sys"
version.workspace = true
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alkanes-cli-common = { path = "../alkanes-cli-common", features = ["web-compat", "wasm-inspection"] }
alkanes-asc = { path = "../alkanes-asc" }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
wasm-bindgen-futures = "0.4"
gloo-timers = "0.3.0"
gloo-utils = "0.1.7"
js-sys = "0.3"
serde_json = { workspace = true }
web-sys = { version = "0.3", features = ["console", "FileList", "HtmlInputElement", "File", "Navigator", "Clipboard", "ClipboardEvent", "CanvasRenderingContext2d", "HtmlCanvasElement", "Window", "Document", "Storage", "Performance", "Crypto", "SubtleCrypto", "CryptoKey", "ResponseInit", "Request", "RequestInit", "RequestMode", "Response", "Headers"] }
bitcoin = { workspace = true }
bip39 = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }
alkanes-support = { workspace = true }
prost = { workspace = true }

sha2 = { workspace = true }
sha3 = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
protobuf = { workspace = true }
pbkdf2 = { workspace = true }
aes-gcm = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
getrandom = { version = "0.2", features = ["js"] }
