[package]
name = "alkanes-std-test"
version = "0.6.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alkanes-runtime = { workspace = true, features = ["panic-hook"] }
alkanes-support = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
metashrew-support = { workspace = true }
sha2 = "0.10.8"
